/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited.
// It is auto-generated by Next.js and updated automatically.
// See: https://nextjs.org/docs/app/building-your-application/configuring/typescript
